# Generated by Django 4.0.1 on 2022-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_location_profile_created_on_profile_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
