# Generated by Django 4.0.1 on 2022-01-13 15:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0008_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='voters_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
