# Generated by Django 4.0.1 on 2022-01-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0009_votes_voters_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='id_number',
            field=models.IntegerField(max_length=30),
        ),
    ]
