# Generated by Django 4.0.1 on 2022-01-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0010_alter_votes_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
