# Generated by Django 4.0.1 on 2022-01-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0011_alter_votes_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='votes',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.gender'),
        ),
    ]
