# Generated by Django 4.0.1 on 2022-01-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0012_gender_alter_votes_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voters.gender'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voters.location'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voters.profile'),
        ),
    ]
